name: mazaoapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.7.0
  cloud_firestore: ^5.4.5
  firebase_auth: ^5.3.2
  image_picker: ^1.1.2
  firebase_storage: ^12.3.5
  permission_handler: ^11.3.1
  geolocator: ^9.0.2
  geocoding: ^3.0.0
  google_maps_flutter: 2.9.0
  firebase_auth_web: ^5.8.13
  http: ^0.13.5
  google_sign_in: ^5.0.7
  shared_preferences: ^2.0.11
  intl: ^0.18.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/ktlg.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/ktlg.jpg"